name: Deployment Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Installing node.js-16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing dependencies
        run: npm install --no-fund --no-audit
      - name: Linter
        run : npm run eslint
      
